import type { ModelSpec, ModelTier } from "./types";

export const ALL_MODELS: ModelSpec[] = [
  // FREE TIER
  {
    modelId: "qwen/qwen3-coder:free",
    name: "Qwen3 Coder (Free)",
    provider: "qwen",
    tier: "free",
    inputCostPerM: 0,
    outputCostPerM: 0,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    capabilities: ["coding", "tool_calling", "long_context"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: true,
    totalParamsB: 480,
    activeParamsB: 35,
    recommendedFor: ["simple_code_review", "docstring_generation", "test_writing"],
  },
  {
    modelId: "deepseek/deepseek-r1-0528:free",
    name: "DeepSeek R1 (Free)",
    provider: "deepseek",
    tier: "free",
    inputCostPerM: 0,
    outputCostPerM: 0,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    capabilities: ["reasoning", "math", "coding"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: true,
    totalParamsB: 685,
    activeParamsB: 37,
    recommendedFor: ["simple_reasoning", "issue_triage", "commit_message_generation"],
  },
  {
    modelId: "z-ai/glm-4.5-air:free",
    name: "GLM-4.5 Air (Free)",
    provider: "z-ai",
    tier: "free",
    inputCostPerM: 0,
    outputCostPerM: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    capabilities: ["tool_calling", "creative"],
    supportsToolCalling: true,
    isMoe: false,
    isFree: true,
    totalParamsB: 0,
    activeParamsB: 0,
    recommendedFor: ["summarization", "template_responses", "status_checks"],
  },
  {
    modelId: "ollama/qwen3:30b-a3b",
    name: "Qwen3 30B (Local)",
    provider: "ollama",
    tier: "free",
    inputCostPerM: 0,
    outputCostPerM: 0,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    capabilities: ["coding", "tool_calling"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: true,
    totalParamsB: 30,
    activeParamsB: 3,
    recommendedFor: ["local_simple_tasks", "offline_coding", "privacy_sensitive"],
  },
  {
    modelId: "ollama/glm4:9b",
    name: "GLM-4 9B (Local)",
    provider: "ollama",
    tier: "free",
    inputCostPerM: 0,
    outputCostPerM: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    capabilities: ["tool_calling", "creative"],
    supportsToolCalling: true,
    isMoe: false,
    isFree: true,
    totalParamsB: 9,
    activeParamsB: 9,
    recommendedFor: ["local_lightweight", "summaries", "drafts"],
  },
  // STANDARD TIER
  {
    modelId: "deepseek/deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "deepseek",
    tier: "standard",
    inputCostPerM: 0.25,
    outputCostPerM: 0.38,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    capabilities: ["coding", "reasoning", "tool_calling", "agentic"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: false,
    totalParamsB: 685,
    activeParamsB: 37,
    recommendedFor: ["code_review", "pr_description", "bug_analysis", "refactoring"],
  },
  {
    modelId: "qwen/qwen3-235b-a22b-2507",
    name: "Qwen3 235B",
    provider: "qwen",
    tier: "standard",
    inputCostPerM: 0.07,
    outputCostPerM: 0.46,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    capabilities: ["coding", "reasoning", "tool_calling", "long_context"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: false,
    totalParamsB: 235,
    activeParamsB: 22,
    recommendedFor: ["code_review", "documentation", "general_analysis"],
  },
  {
    modelId: "qwen/qwen3-30b-a3b",
    name: "Qwen3 30B-A3B",
    provider: "qwen",
    tier: "standard",
    inputCostPerM: 0.06,
    outputCostPerM: 0.22,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    capabilities: ["coding", "tool_calling"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: false,
    totalParamsB: 30,
    activeParamsB: 3,
    recommendedFor: ["lightweight_tasks", "formatting", "simple_edits"],
  },
  {
    modelId: "z-ai/glm-4.7",
    name: "GLM-4.7",
    provider: "z-ai",
    tier: "standard",
    inputCostPerM: 0.25,
    outputCostPerM: 1.0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    capabilities: ["coding", "tool_calling", "agentic"],
    supportsToolCalling: true,
    isMoe: false,
    isFree: false,
    totalParamsB: 0,
    activeParamsB: 0,
    recommendedFor: ["tool_heavy_tasks", "multi_step_workflows", "ci_debugging"],
  },
  // PREMIUM TIER
  {
    modelId: "deepseek/deepseek-r1-0528",
    name: "DeepSeek R1",
    provider: "deepseek",
    tier: "premium",
    inputCostPerM: 0.40,
    outputCostPerM: 1.75,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    capabilities: ["reasoning", "math", "coding", "agentic"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: false,
    totalParamsB: 685,
    activeParamsB: 37,
    recommendedFor: ["complex_debugging", "architecture_decisions", "security_review"],
  },
  {
    modelId: "qwen/qwen3-coder",
    name: "Qwen3 Coder 480B",
    provider: "qwen",
    tier: "premium",
    inputCostPerM: 0.22,
    outputCostPerM: 0.95,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    capabilities: ["coding", "tool_calling", "long_context", "agentic"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: false,
    totalParamsB: 480,
    activeParamsB: 35,
    recommendedFor: ["heavy_refactoring", "new_feature_implementation", "codebase_migration"],
  },
  {
    modelId: "z-ai/glm-5",
    name: "GLM-5",
    provider: "z-ai",
    tier: "premium",
    inputCostPerM: 1.0,
    outputCostPerM: 3.2,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    capabilities: ["coding", "reasoning", "tool_calling", "agentic", "creative"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: false,
    totalParamsB: 745,
    activeParamsB: 44,
    recommendedFor: ["agentic_workflows", "creative_content", "complex_tool_chains"],
  },
  {
    modelId: "moonshotai/kimi-k2",
    name: "Kimi K2",
    provider: "moonshotai",
    tier: "premium",
    inputCostPerM: 0.39,
    outputCostPerM: 1.90,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    capabilities: ["coding", "reasoning", "tool_calling", "agentic"],
    supportsToolCalling: true,
    isMoe: true,
    isFree: false,
    totalParamsB: 1000,
    activeParamsB: 32,
    recommendedFor: ["multi_step_agents", "long_horizon_tasks", "research"],
  },
];

export function getModelsByTier(tier: ModelTier): ModelSpec[] {
  return ALL_MODELS.filter((m) => m.tier === tier);
}

export function estimateCost(model: ModelSpec, inputTokens: number, outputTokens: number): number {
  return (inputTokens / 1_000_000) * model.inputCostPerM + (outputTokens / 1_000_000) * model.outputCostPerM;
}

export const TIER_COLORS: Record<ModelTier, string> = {
  free: "#22c55e",
  standard: "#3b82f6",
  premium: "#f59e0b",
};

export const PROVIDER_LABELS: Record<string, string> = {
  deepseek: "DeepSeek",
  qwen: "Alibaba Qwen",
  "z-ai": "Zhipu AI",
  moonshotai: "Moonshot",
  ollama: "Ollama (Local)",
};
